chore: set up cloudbuild file
pagerinc/minion pull request #524
Opened 2023-04-20 13:52 UTC by peter-vizi-pager

2023-06-01 15:26 UTC, BlaineEhrhart requested changes

2023-06-01 15:26 UTC, BlaineEhrhart commented on lib/index.js
> +    Debug('creating Jackrabbit instance with url %s', rabbitUrl);
Can't this leak the password for the rabbit connection?

2023-06-01 15:26 UTC, BlaineEhrhart commented on package.json
> +    "eslint": "7.x",
Why downgrade?

2023-06-01 17:10 UTC, peter-vizi-pager commented on package.json
> +    "eslint": "7.x",
At the moment `@pager/eslint-config` supports 7: https://github.com/pagerinc/eslint-config/blob/4bb49d68c1263e01139de8ca10c0ea7436dac23b/package.json#L23 I think Joan has startet looking into upgrading that but I'm not sure if that work is ready yet.

2023-06-01 18:54 UTC, IJuanI commented on cloudbuild.yaml
> +    name: 'gcr.io/$PROJECT_ID/cloudbuilders/npm:6.13.4'
This is an old version of npm, node v18.12.1 uses npm v8.19.2

2023-06-01 18:57 UTC, BlaineEhrhart approved these changes

2023-06-02 15:51 UTC, merged

2023-06-05 18:07 UTC, sa-pagerinc-automation commented
:tada: This PR is included in version 3.8.1 :tada:

The release is available on [GitHub release](https://github.com/pagerinc/minion/releases/tag/v3.8.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: